modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "saplanting"
version = "${version}"
displayName = "saplanting"
authors = "MUYU_Twilighter"
description = '''

'''
#logoFile = ""

[[dependencies.saplanting]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saplanting]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "saplanting.mixins.json"
